    op.create_table('dim_date',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_id', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('epoch', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('day_suffix', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('day_name', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week_iso', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_quarter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_id', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('week_id_iso', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('week_name', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('week_name_iso', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('week_of_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_of_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_of_year_id', sa.CHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('week_of_year_iso', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_of_year_iso_id', sa.CHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('month_of_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month_name', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('month_name_abbreviated', sa.CHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('quarter_of_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quarter_name', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('quarter_id', sa.CHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('yyyy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_day_of_week', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_day_of_week', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('first_day_of_week_iso', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_day_of_week_iso', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('first_day_of_month', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_day_of_month', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('first_day_of_quarter', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_day_of_quarter', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('first_day_of_year', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_day_of_year', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('mmyyyy', sa.CHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('mmddyyyy', sa.CHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('weekend_indr', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dim_date_pkey'),
    sa.UniqueConstraint('date_id', name='dim_date_date_id_key')
    )
    op.create_index('idx_dim_date_year', 'dim_date', ['yyyy'], unique=False)
    op.create_index('idx_dim_date_week_ending', 'dim_date', ['last_day_of_week'], unique=False)
    op.create_index('idx_dim_date_month_ending', 'dim_date', ['last_day_of_month'], unique=False)
