"""Initial build

Revision ID: ec3916939776
Revises: 
Create Date: 2022-12-10 12:04:34.928018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3916939776'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Date(), nullable=False),
    sa.Column('epoch', sa.BigInteger(), nullable=False),
    sa.Column('day_suffix', sa.String(length=4), nullable=False),
    sa.Column('day_name', sa.String(length=9), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('day_of_week_iso', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('day_of_quarter', sa.Integer(), nullable=False),
    sa.Column('day_of_year', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.String(length=7), nullable=False),
    sa.Column('week_id_iso', sa.String(length=7), nullable=False),
    sa.Column('week_name', sa.String(length=3), nullable=False),
    sa.Column('week_name_iso', sa.String(length=3), nullable=False),
    sa.Column('week_of_month', sa.Integer(), nullable=False),
    sa.Column('week_of_year', sa.Integer(), nullable=False),
    sa.Column('week_of_year_id', sa.CHAR(length=10), nullable=False),
    sa.Column('week_of_year_iso', sa.Integer(), nullable=False),
    sa.Column('week_of_year_iso_id', sa.CHAR(length=10), nullable=False),
    sa.Column('month_of_year', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=9), nullable=False),
    sa.Column('month_abbr', sa.CHAR(length=3), nullable=False),
    sa.Column('quarter_of_year', sa.Integer(), nullable=False),
    sa.Column('quarter_name', sa.String(length=9), nullable=False),
    sa.Column('quarter_id', sa.CHAR(length=6), nullable=False),
    sa.Column('yyyy', sa.Integer(), nullable=False),
    sa.Column('week_from', sa.Date(), nullable=False),
    sa.Column('week_thru', sa.Date(), nullable=False),
    sa.Column('week_from_iso', sa.Date(), nullable=False),
    sa.Column('week_thru_iso', sa.Date(), nullable=False),
    sa.Column('month_from', sa.Date(), nullable=False),
    sa.Column('month_thru', sa.Date(), nullable=False),
    sa.Column('quarter_from', sa.Date(), nullable=False),
    sa.Column('quarter_thru', sa.Date(), nullable=False),
    sa.Column('year_from', sa.Date(), nullable=False),
    sa.Column('year_thru', sa.Date(), nullable=False),
    sa.Column('mmyyyy', sa.CHAR(length=6), nullable=False),
    sa.Column('mmddyyyy', sa.CHAR(length=10), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_id'),
    schema='date_dim'
    )
    op.create_index(op.f('ix_date_dim_dim_date_month_thru'), 'dim_date', ['month_thru'], unique=False, schema='date_dim')
    op.create_index(op.f('ix_date_dim_dim_date_week_thru'), 'dim_date', ['week_thru'], unique=False, schema='date_dim')
    op.create_index(op.f('ix_date_dim_dim_date_yyyy'), 'dim_date', ['yyyy'], unique=False, schema='date_dim')
    op.create_table('dim_date_dev',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_id'),
    schema='date_dim'
    )
    op.drop_index('idx_dim_date_month_thru', table_name='dim_date')
    op.drop_index('idx_dim_date_week_thru', table_name='dim_date')
    op.drop_index('idx_dim_date_year', table_name='dim_date')
    op.drop_table('dim_date')
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.create_table('dim_date',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_id', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('epoch', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('day_suffix', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('day_name', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week_iso', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_quarter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_id', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('week_id_iso', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('week_name', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('week_name_iso', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('week_of_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_of_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_of_year_id', sa.CHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('week_of_year_iso', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_of_year_iso_id', sa.CHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('month_of_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month_name', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('month_abbr', sa.CHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('quarter_of_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quarter_name', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('quarter_id', sa.CHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('yyyy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('week_thru', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('week_from_iso', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('week_thru_iso', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('month_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('month_thru', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quarter_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quarter_thru', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('year_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('year_thru', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('mmyyyy', sa.CHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('mmddyyyy', sa.CHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_weekend', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dim_date_pkey'),
    sa.UniqueConstraint('date_id', name='dim_date_date_id_key')
    )
    op.create_index('idx_dim_date_year', 'dim_date', ['yyyy'], unique=False)
    op.create_index('idx_dim_date_week_thru', 'dim_date', ['week_thru'], unique=False)
    op.create_index('idx_dim_date_month_thru', 'dim_date', ['month_thru'], unique=False)
    op.drop_table('dim_date_dev', schema='date_dim')
    op.drop_index(op.f('ix_date_dim_dim_date_yyyy'), table_name='dim_date', schema='date_dim')
    op.drop_index(op.f('ix_date_dim_dim_date_week_thru'), table_name='dim_date', schema='date_dim')
    op.drop_index(op.f('ix_date_dim_dim_date_month_thru'), table_name='dim_date', schema='date_dim')
    op.drop_table('dim_date', schema='date_dim')
    # ### end Alembic commands ###
